const screenName = {
  login: "Login",
  forgotPassword: "ForgotPassword",
  resetPassword: "ResetPassword",
  createAccount: "CreateAccount",
  verification: "Verification",
  checkEmail: "CheckEmail",
  introduction: "Introduction",
  splash: "Splash",
  suggestFriend: "SuggestFriend",
  tellUsAboutLooksLike: "TellUsAboutLooksLike",
  tellUsAboutTags: "TellUsAboutTags",
  tellUsAboutSize: "TellUsAboutSize",
  suggestStore: "SuggestStore",
  drawerNavigation: "drawerNavigation",
  searchResultScreen: "SearchResultScreen",
  mPin: "Mpin",
  messageChatScreen: "MessageChatScreen",
  addProductImage: "AddProductImage",
  postCategory: "PostCategory",
  itemDetail: "ItemDetail",
  productPreview: "ProductPreview",
  postData: "PostData",
  // bottomNavigation home route
  homeScreenIcons: "HomeScreenIcons",
  mainHome: "Main Home",
  productDetail: "ProductDetail",
  messagesHome: "MessagesHome",
  notification: "Notification",
  // bottom Tab Screens
  bottomNavigationHomeRoute: "bottomNavigationHomeRoute",
  bottomNavigationSearchRoute: "bottomNavigationSearchRoute",
  search: "Search",
  postItem: "PostItem",
  message: "Message",
  profile: "Profile",
  bookmarkScreen: "BookmarkScreen",
  // Top Tab Screens
  explore: "Explore",
  feed: "Feed",
  // drawerScreen
  bottomNavigation: "bottonNavigation",
  subscription: "Subscription",
  authRoute: "AuthRoute",
  profileRoute: "ProfileRoute",
  editProfile: "EditProfile",
  myAds: "MyAds",
  otherUserProfile: "OtherUserProfile",
  termsAndCondition: "TermsAndCondition",
  aboutUs: "AboutUs",
  homeScreen: "HomeScreen",
  referToFriend: "ReferToFriend",
  playStoreRating: "PlayStoreRating",
  privacyPolicy: "PrivacyPolicy",
};

export default screenName;
